config/routes.rb
Rails.application.routes.draw do

  root 'groups#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users
  resources :groups do
    resource :user_groups, only: [:create, :destroy]
    resources :lists, only: [:show, :create, :destroy, :edit, :update] do
      member do
        get :switch
      end
      resources :tasks, only: [:create, :destroy] do
        member do
          get :change
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups

  has_many :lists, dependent: :destroy

  def grouped_by?(user)
    user_groups.where(user_id: user.id).exists?
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :group
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :tasks
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @groups = Group.all
    @new_group = Group.new
    @user = current_user
  end

  def show
    @group = Group.find(params[:id])
    @users = @group.users
    @list = List.new
  end

  def new
    @group = Group.new
  end

  def create
    @user = current_user
    @group = @user.groups.new(group_params)
    if @user.save
      redirect_to groups_path
    else
      redirect_to new_group_path
    end
  end


  private
    def group_params
      params.require(:group).permit(:title, :color)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
  end

  def create
    @list = List.new(list_params)
    @group = Group.find(params[:group_id])
    @list.group_id = @group.id
    @list.save
    redirect_to groups_path
  end

  def show
    @list = List.find(params[:id])
    @group = @list.group
    @tasks = @list.tasks
  end

  def edit
    @group = Group.find(params[:group_id])
    @list = List.find(params[:id])
  end

  def update
    @group = Group.find(params[:group_id])
    @list = List.find(params[:id])
    @list.update(params.require(:list).permit(:title, :color))
    redirect_to group_path(@group)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to groups_path
  end

  def switch
    # todoリストに表示するか否かの関数
    @list = List.find(params[:id])
    if @list.indication == 0
      @list.indication = 1
    else
      @list.indication = 0
    end
    @list.save
    redirect_to groups_path
  end

  private
    def list_params
      params.require(:list).permit(:title, :color)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def show
  end

  def create
    @user = current_user
    @task = @user.tasks.new(task_params)
    @list = List.find(params[:list_id])
    @task.list_id = @list.id
    @task.todo = 0
    @task.save
    # pathのために生成
    @group = Group.find(params[:group_id])
    redirect_to group_list_path(@group, @list)
  end

  def destroy
    # @group = Group.find(params[:group_id])
    # @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to groups_path
  end

  # todo,doing,doneを移動させる関数
  def change
    # @group = Group.find(params[:group_id])
    # @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    if @task.todo == 0
      @task.todo = 1
      @task.save
      redirect_to groups_path
    elsif @task.todo == 1
      @task.todo = 2
      @task.save
      redirect_to groups_path
    # elsif @task.todo == 2
    #   @task.delete  # destroyは親も死ぬ
    #   redirect_to groups_path
    end
  end

  private
    def task_params
      params.require(:task).permit(:title, :body, :target_date)
    end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController

  def create
    user_group = current_user.user_groups.build(group_id: params[:group_id])
    user_group.save
    redirect_to groups_path
  end

  def destroy
    user_group = UserGroup.find_by(group_id: params[:group_id], user_id: current_user.id)
    user_group.destroy
    redirect_to groups_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @groups = @user.groups
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
  <%= stylesheet_link_tag 'groups', media: 'all', 'data-turbolinks-track': 'reload' %>


<div class="aside">
  <div class="username">
    <% if user_signed_in? %>
      <h2 style="font-weight: bold"><%= current_user.username %></h2>
    <% else %>
      <h2>未ログイン</h2>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="check">
      <input type="checkbox" id="test">
      <h2>ホーム</h2>
    </div>

    <div class="hidden_box">
      <label for="label1">>マイグループ</label>
      <input type="checkbox" id="label1">
      <div class="hidden_show">
        <ul class="gnav">
          <% current_user.groups.each do |group| %>
            <li>

              <% if false %>
                <a href="" class="js-modal-open" data-target="modal02"><%= group.title %></a>
                <div id="modal02" class="modal js-modal">
                  <div class="modal__bg js-modal-close"></div>
                  <div class="modal__content">
                    <%# ここからモーダルメニュー %>
                    <h1><%= group.title %></h1>
                    <hr>
                    <p><span>グループ名: </span><%= group.title %></p>
                    <hr>
                    <p><span>参加人数： </span><%= group.user_groups.count %>人</p>
                    <hr>
                    <% group.users.each do |user| %>
                    <p><span>参加ユーザー名: </span><%= user.username %></p>
                    <% end %>
                    <hr>
                    <% if group.lists.exists? %>
                      <% group.lists.each do |list| %>
                        <p><span>登録リスト名: </span><%= list.title %></p>
                      <% end %>
                    <% else %>
                      <p>リストは現在登録されていません</p>
                    <% end %>
                    <hr>
                  </div>
                </div>
                <ul>
                  <% if group.lists.exists? %>
                    <% group.lists.each do |list| %>
                      <li><%= list.title %></li>
                    <% end %>
                  <% else %>
                    <li>リストはありません</li>
                  <% end %>
                </ul>
              <% end %>

              <%= link_to group.title, group_path(group.id) %>
              <ul>
                <% if group.lists.exists? %>
                  <% group.lists.each do |list| %>
                    <li>
                      <% if list.indication == 0 %>
                        <%= link_to "○", switch_group_list_path(group,list) %>
                      <% else %>
                        <%= link_to "×", switch_group_list_path(group,list) %>
                      <% end %>
                      <%= link_to list.title, group_list_path(group,list) %>
                    </li>
                  <% end %>
                <% else %>
                  <li>リストはありません</li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>



  <div class="check">
    <input type="checkbox" id="test"/>
    <h2>何かいれるかも</h2>
  </div>


  <% if user_signed_in? %>
    <div class="hidden_box">
      <label for="label2">>未参加グループ名</label>
      <input type="checkbox" id="label2">
      <div class="hidden_show">
        <ul class="gnav">
          <% @groups.each do |group| %>
            <% unless group.grouped_by?(current_user) %>
              <li>
                <%= link_to group.title, group_path(group.id) %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="check">
      <a href="" class="js-modal-open" data-target="modal01">新規グループ作成</a>
      <div id="modal01" class="modal js-modal">
        <div class="modal__bg js-modal-close"></div>
        <div class="modal__content">
          <%# ここからモーダルメニュー %>
          <h1>【新規グループ作成】</h1>
          <%= form_with(model: @new_group, local: true, url: groups_path) do |form| %>
            <p>
              <%= form.label :title, "グループ名" %>
              <%= form.text_field :title %>
              <br>
              <%= form.label :color, "グループの色" %>
              <%= form.text_field :color %>
            </p>
            <%= form.submit %>
          <% end %>
          <a class="js-modal-close" href="">閉じる</a>
        </div>
      </div>
    </div>
  <% end %>
  
</div>




<% if false %>

  <% @groups.each do |group| %>
    <p><span>グループ名: </span><%= link_to group.title, groups_path(group.id) %></p>

    <% if user_signed_in? %>
      <% if group.grouped_by?(current_user) %>
        <p><span>グループを退会: </span><%= link_to group.user_groups.count, group_user_groups_path(group.id), method: :delete %></p>
      <% else %>
        <p><span>グループに参加: </span><%= link_to group.user_groups.count, group_user_groups_path(group.id), method: :post %></p>
      <% end %>
    <% else %>
      <p><span>参加人数: </span><%= group.user_groups.count %></p>
    <% end %>
    <hr>
  <% end %>

  <h2>グループ新規作成</h2>
  <%= form_with(model: @group, url: groups_path, local: true) do |form| %>
    <p>
      <%= form.label :title, "グループ名" %>
      <%= form.text_field :title %>
      <br>
      <%= form.label :color, "グループの色" %>
      <%= form.text_field :color %>
    </p>
    <%= form.submit %>
  <% end %>

<% end %>







<!-- -------------------------------------------------------------------------------- -->


<div class="todo">
  <h3>todo</h3>
  <hr>
  <% @groups.each do |group| %>
    <% group.lists.each do |list| %>
      <% if list.indication == 1 %>
        <% list.tasks.each do |task| %>
          <% if task.todo == 0 %>
            <div class="sample">
              <h4>タスクタイトル：「<%= task.title %>」(リスト：<%= list.title %>)</h4>
              <hr>
              <p>内容：<%= task.body %></p>
              <hr>
              <p>締切：<%= task.target_date %></p>
              <hr>
              <p><%= link_to "doingに移動", change_group_list_task_path(group, list, task) %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="doing">
  <h3>doing</h3>
  <hr>
  <% @groups.each do |group| %>
    <% group.lists.each do |list| %>
      <% if list.indication == 1 %>
        <% list.tasks.each do |task| %>
          <% if task.todo == 1 %>
            <div class="sample">
              <h4>タスクタイトル：「<%= task.title %>」(リスト：<%= list.title %>)</h4>
              <hr>
              <h4>リストタイトル：「<%= list.title %>」</h4>
              <hr>
              <p>内容：<%= task.body %></p>
              <p><%= link_to "doneに移動", change_group_list_task_path(group, list, task) %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="done">
  <h3>done</h3>
  <hr>
  <% @groups.each do |group| %>
    <% group.lists.each do |list| %>
      <% if list.indication == 1 %>
        <% list.tasks.each do |task| %>
          <% if task.todo == 2 %>
            <div class="sample">
              <h4>タスクタイトル：「<%= task.title %>」</h4>
              <hr>
              <h4>リストタイトル：「<%= list.title %>」</h4>
              <hr>
              <p>内容：<%= task.body %></p>
              <hr>
              <p><%= link_to "タスクをリストから削除", group_list_task_path(group, list, task), method: :delete, data:{ confirm: 'Sure?'} %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/groups/new.html.erb
<h1>Groups#new(新規グループ作成)</h1>
<p>Find me in app/views/groups/new.html.erb</p>

<%= form_with(model: @group, local: true) do |form| %>
  <p>
    <%= form.label :title, "グループ名" %>
    <%= form.text_field :title %>
    <br>
    <%= form.label :color, "グループの色" %>
    <%= form.text_field :color %>
  </p>
  <%= form.submit %>
<% end %>

app/views/groups/show.html.erb
<%= stylesheet_link_tag 'groups-show', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1>Groups#show(グループ詳細)</h1>
<p>Find me in app/views/groups/show.html.erb</p>
<hr>

<p><span>グループ名: </span><%= @group.title %></p>
<hr>

<p><span>参加人数： </span><%= @group.user_groups.count %>人</p>
<hr>

<% @users.each do |user| %>
  <p><span>参加ユーザーメアド: </span><%= link_to user.email, user_path(user.id) %></p>
<% end %>
<hr>

<% if @group.lists.exists? %>
  <% @group.lists.each do |list| %>
    <p>
      <span>リスト名: </span><%= link_to list.title, group_list_path(@group, list), method: :get %>
      <%= link_to "[編集]", edit_group_list_path(@group, list), method: :get %>
      <%= link_to "[削除]", group_list_path(@group, list), method: :delete, data:{ confirm: 'Sure?'} %>
    </p>
  <% end %>
<% else %>
  <p>リストは現在登録されていません</p>
<% end %>
<hr>

<% if @group.grouped_by?(current_user) %>

  <p>リスト新規作成</p>
  <%= form_with(model: [@group, @list], local: true, url: group_lists_path(@group)) do |form| %>
    <p>
      <%= form.label :title, "リスト名　" %>
      <%= form.text_field :title %>
      <br>
      <%= form.label :color, "リストの色" %>
      <%= form.text_field :color %>
    </p>
    <br>
  <%= form.submit %>
  <% end %>
  <br>
  <p><%= link_to "グループから退会", group_user_groups_path(@group.id), method: :delete %></p>
<% else %>
  <p><%= link_to "グループに参加", group_user_groups_path(@group.id), method: :post %></p>
<% end %>
<hr>
<br>

<%= link_to ">戻る", groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>タスク管理ツール</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div>
        <h2>タスク管理ツール(仮)</h2>
      </div>
      <div>
        <%= link_to "TOP画面", groups_path %>
        <% if user_signed_in? %>  <!-- deviseのメソッドで、「ログインしているかしていないかでtrue or falseを返す」メソッド -->
          <%= link_to "マイページ", user_path(current_user.id) %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "ユーザー新規登録", new_user_registration_path %>
          <%= link_to "ログイン", new_user_session_path %>
        <% end %>
        <%= link_to "(ユーザー一覧)", users_path %>
      </div>
    </header>

    <main>
    <%= yield %>
    </main>

    <footer>
      <h2>footer</h2>
      <p>フッターはいらないかも</p>
    </footer>


    <script>
    $(function(){
      $('.js-modal-open').each(function(){
        $(this).on('click',function(){
          var target = $(this).data('target');
          var modal = document.getElementById(target);
          // $(".gnav ul li").css("display", "none");
          $(modal).fadeIn(200);
          return false;
        });
      });
      $('.js-modal-close').on('click',function(){
        $('.js-modal').fadeOut(200);
        return false;
      });

      // $(".gnav li").hover(
      //   function() {
      //   $("this ul").css("display", "block");
      // },
      // function() {
      //   $("this").children("ul").css("display", "none");
      // }
      // )
    });
    </script>
  </body>
</html>

app/views/lists/edit.html.erb
<%= stylesheet_link_tag 'lists-show', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>



<p>リスト編集</p>
<%= form_with(model: [@group, @list], local: true, url: group_list_path(@group)) do |form| %>
  <p>
    <%= form.label :title, "リスト名　" %>
    <%= form.text_field :title %>
    <br>
    <%= form.label :color, "リストの色" %>
    <%= form.text_field :color %>
  </p>
  <br>
<%= form.submit "編集する"%>
<% end %>
<br>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/show.html.erb
<%= stylesheet_link_tag 'lists-show', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1>Lists#show(リスト詳細)</h1>
<p>Find me in app/views/lists/show.html.erb</p>
<hr>

<p><span>リスト名: </span><%= @list.title %></p>
<hr>
<p><span>登録タスク数: </span><%= @list.tasks.count %>個</p>
<hr>

<% if @list.tasks.exists? %>
  <% @list.tasks.each do |task| %>
    <p><span>タスク名: </span><%= task.title %></p>
  <% end %>
<% else %>
  <p>タスクは現在登録されていません</p>
<% end %>
<hr>

<% @group.users.each do |user| %>
  <p><%= user.username %></p>
<% end %>

<p>新規タスク作成</p>
<%= form_with(model: [@list, @list.tasks.build], url: group_list_tasks_path(@group, @list), local: true) do |form| %>
  <p>
    <%= form.label :title, "タスクタイトル" %>
    <%= form.text_field :title %>
    <br>
    <%= form.label :body, "タスク内容　　" %>
    <%= form.text_area :body %>
    <br>
    <%= form.label :target_date, "終了予定日程　" %>
    <%= form.date_field :target_date %>
    <br>
    <% if false %>
      <%= form.label :test, "プルダウンテスト" %>
      <%= form.select :test, [["1", "1"], ["2", "2"], ["3", "3"]] %>
      <br>
      <%= form.label :test, "作業者　　　" %>
      <%= form.collection_select :test, @group.users.all, :prompt => "作業者を選択" %>
    <% end %>
  </p>
  <br>
  <%= form.submit %>
<% end %>
<br>
<hr>
<%= link_to ">戻る", groups_path %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index(ユーザー一覧)</h1>
<p>Find me in app/views/users/index.html.erb</p>
<hr>

<% @users.each do |user| %>
  <p><span>ユーザー名　　: </span><%= link_to user.username, user_path(user.id) %></p>
  <p><span>メールアドレス: </span><%= link_to user.email, user_path(user.id) %></p>
  <hr>
<% end %>

app/views/users/show.html.erb
<h1>Users#show(マイページ)</h1>
<p>Find me in app/views/users/show.html.erb</p>
<hr>

<p><span>ログインユーザー名　　: </span><%= link_to @user.username, user_path(@user.id) %></p>
<p><span>ログインユーザーメアド: </span><%= link_to @user.email, user_path(@user.id) %></p>
<hr>

<% @groups.each do |group| %>
  <p><span>参加グループ名: </span><%=link_to group.title, group_path(group.id) %></p>
  <hr>
<% end %>